targets:
  $default:
    builders:
#      json_serializable: # couldn't use the damn generated .g.dart in the builder for some reason
#        options:
#          create_factory: true
#          nullable: true
      dart_ast_json|resolver: # put AST JSON on a diet
        enabled: True
      dart_ast_json|functionBuilder: # functions
        enabled: True
      dart_ast_json|structBuilder: # structs
        enabled: True
      dart_ast_json|enumBuilder: # enums
        enabled: True

builders:
  resolver:
    import: 'package:dart_ast_json/generators.dart'
    builder_factories: ['resolver']
    build_extensions:
      .json:
        - .ejson
        - .fjson
        - .sjson
        - .tjson
    auto_apply: dependents
    build_to: cache
  enumBuilder:
    import: 'package:dart_ast_json/generators.dart'
    builder_factories: ['enumBuilder']
    build_extensions:
      "$lib$": [ ".e.dart" ]
    required_inputs: ['.ejson']
    auto_apply: dependents
    build_to: source
  functionBuilder:
    import: 'package:dart_ast_json/generators.dart'
    builder_factories: ['functionBuilder']
    build_extensions:
      "$lib$": [ ".f.dart" ]
    required_inputs: ['.tjson', '.fjson']
    auto_apply: dependents
    build_to: source
  structBuilder:
    import: 'package:dart_ast_json/generators.dart'
    builder_factories: ['structBuilder']
    build_extensions:
      "$lib$": [ ".s.dart" ]
    required_inputs: ['.tjson', '.sjson']
    auto_apply: dependents
    build_to: source
