name: dart_ast_json
version: 0.0.1
repository: https://github.com/buggaboo/dart-ast-json
homepage: https://github.com/buggaboo/dart-ast-json/TODO
description: dart build_runner ffi binding generator for any LLVM (> 10.*) ast-dump in JSON

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  analyzer: ">=0.35.0 <0.100.0"
  build: ^1.0.0
  dart_style: ^1.3.0
  ffi: ^0.1.3
  glob: ^1.1.0
  path: ^1.6.0
  source_gen: ^0.9.0
  petitparser: ^3.0.2
#  json_annotation: ^3.0.0 // used it once, and nevermore

# ffi_tool: ^0.2.5 # it could have been useful...

dev_dependencies:
  build_config: ^0.4.1+1
  build_runner: ^1.6.6
  pedantic: ^1.7.0
  test: ^1.5.0
  json_serializable: ^3.2.0
